import cloneDeep from 'lodash/cloneDeep';

const createYouTubeImageLink = (videoId) => {
    return 'https://img.youtube.com/vi/' + videoId + '/hqdefault.jpg'
}

const initialState = {
    score: 0,
    materials: [
        {
            key: 0,
            hint: 'Shuffle',
            image: 'https://media.istockphoto.com/vectors/shuffle-icon-filled-shuffle-icon-for-website-design-and-mobile-app-vector-id1168505957?b=1&k=6&m=1168505957&s=612x612&w=0&h=qtf1JFqKkv4UqsXcbhw7GHJrJXxzrSLGfxvztP1tVhI=',
            mainText: 'Shuffle',
            title: '',
            linkToMaterial: 'https://ru.wikipedia.org/wiki/%D0%A8%D0%B0%D1%84%D1%84%D0%BB',
            tasks: []
        },
        {
            key: 1,
            hint: 'Programming dictionary',
            image: 'https://repository-images.githubusercontent.com/155638338/82ecf400-6f73-11e9-8908-dfadfe1aa923',
            mainText: 'Programming dictionary',
            title: '',
            linkToMaterial: 'https://en.wikipedia.org/wiki/Computer_programming',
            tasks: [
                 {russianWord: 'надежный', correctAnswer: 'robust', complexity: 60},
                 {russianWord: 'устойчивый', correctAnswer: 'resilient', complexity: 60},
                 {russianWord: 'выставить', correctAnswer: 'expose', complexity: 60},
                 {russianWord: 'крупнозернистый', correctAnswer: 'coarse-grained', complexity: 60},
                 {russianWord: 'мелкозернистый', correctAnswer: 'fine-grained', complexity: 60},
                 {russianWord: 'переборка', correctAnswer: 'bulkhead', complexity: 60},
                 {russianWord: 'разделять', correctAnswer: 'compartmentalize', complexity: 60},
                 {russianWord: 'галстук, привязать', correctAnswer: 'tie', complexity: 60},
                 {russianWord: 'безжалостно', correctAnswer: 'ruthlessly', complexity: 60},
                 {russianWord: 'связанный', correctAnswer: 'coupled', complexity: 60},
                 {russianWord: 'предусмотрительность', correctAnswer: 'forethought', complexity: 60},
                 {russianWord: 'огромный', correctAnswer: 'tremendous', complexity: 60},
                 {russianWord: 'быть похороненным', correctAnswer: 'getting buried', complexity: 60},
                 {russianWord: 'специальный', correctAnswer: 'ad hoc', complexity: 60},
                 {russianWord: 'свидетель', correctAnswer: 'witness', complexity: 60},
                 {russianWord: 'кусок', correctAnswer: 'chunk', complexity: 60},
                 {russianWord: 'разъединять', correctAnswer: 'tease apart', complexity: 60},
                 {russianWord: 'болтливый', correctAnswer: 'chatty', complexity: 60},
                 {russianWord: 'подрыв', correctAnswer: 'subvert', complexity: 60},
                 {russianWord: 'разрастание', correctAnswer: 'sprawl', complexity: 60},
                 {russianWord: 'огромный', correctAnswer: 'tremendous', complexity: 60},
                 {russianWord: 'избегать', correctAnswer: 'eschew [эшеф]', complexity: 60},
                 {russianWord: 'строгость', correctAnswer: 'rigor', complexity: 60},
                 {russianWord: 'снесённый', correctAnswer: 'torn down', complexity: 60},
                 {russianWord: 'сборка', correctAnswer: 'assembly', complexity: 60},
                 {russianWord: 'перебои в работе', correctAnswer: 'outage', complexity: 60},
                 {russianWord: 'поверхность', correctAnswer: 'surface', complexity: 60},
                 {russianWord: 'невыполнимо', correctAnswer: 'unfeasible', complexity: 60},
                 {russianWord: 'задержка', correctAnswer: 'latency', complexity: 60},
                 {russianWord: 'одноразовый', correctAnswer: 'disposable', complexity: 60},
                 {russianWord: 'обманчиво', correctAnswer: 'deceptively', complexity: 60},
                 {russianWord: 'узкий', correctAnswer: 'narrow', complexity: 60},
                 {russianWord: 'границы', correctAnswer: 'boundaries', complexity: 60},
                 {russianWord: 'обыденное', correctAnswer: 'mundane', complexity: 60},
            ]
        },
        {
            key: 2,
            hint: 'Getting Pushed Off After Sex - Whitney Cummings',
            image: createYouTubeImageLink('F5hA5vuQ9AM'),
            mainText: 'Getting Pushed Off After Sex - Whitney Cummings',
            title: '',
            linkToMaterial: 'https://www.youtube.com/watch?v=F5hA5vuQ9AM&ab_channel=ComedyCentralStand-Up',
            tasks: [
                {russianWord: 'интенсивный', correctAnswer: 'intense', complexity: 60},
                {russianWord: 'скрученный', correctAnswer: 'twisted', complexity: 60},
                {russianWord: 'относиться', correctAnswer: 'treat', complexity: 60},
                {russianWord: 'спешиваться', correctAnswer: 'dismount', complexity: 60},
                {russianWord: 'вера', correctAnswer: 'faith', complexity: 60},
                {russianWord: 'связка', correctAnswer: 'bunch', complexity: 60},
                {russianWord: 'лазанья', correctAnswer: 'lasagna', complexity: 60},
                {russianWord: 'лодыжка', correctAnswer: 'ankle', complexity: 60},
                {russianWord: 'понимать', correctAnswer: 'figure out', complexity: 60},
                {russianWord: 'смущающий', correctAnswer: 'embarrasing', complexity: 60},
                {russianWord: 'странный', correctAnswer: 'weird', complexity: 60},
				{russianWord: 'тусоваться', correctAnswer: 'hang out', complexity: 60},
                {russianWord: 'преследование', correctAnswer: 'stalking', complexity: 60},
                {russianWord: 'одержимый', correctAnswer: 'obsessed', complexity: 60},
                {russianWord: 'самый подлый', correctAnswer: 'meanest', complexity: 60},
                {russianWord: 'раздражительный ', correctAnswer: 'irritable', complexity: 60},
                {russianWord: 'обиженный', correctAnswer: 'resentful', complexity: 60},
                {russianWord: 'вдыхать', correctAnswer: 'inhale', complexity: 60},
                {russianWord: 'зажигать', correctAnswer: 'lit up', complexity: 60},
                {russianWord: 'пытка', correctAnswer: 'torture', complexity: 60},
                {russianWord: 'обратный огонь', correctAnswer: 'backfiring', complexity: 60},
                {russianWord: 'голодающий', correctAnswer: 'starving', complexity: 60},
                {russianWord: 'страстный', correctAnswer: 'passionate', complexity: 60},
                {russianWord: 'консервная банка', correctAnswer: 'tin can', complexity: 60},
                {russianWord: 'стержень', correctAnswer: 'rod', complexity: 60},
                {russianWord: 'брюшной', correctAnswer: 'abdominal', complexity: 60},
                {russianWord: 'сводит меня с ума', correctAnswer: 'drive me nuts', complexity: 60},
                {russianWord: 'оскорбительный', correctAnswer: 'insulting', complexity: 60},
                {russianWord: 'потомство', correctAnswer: 'offspring', complexity: 60}
            ]
        },
        {
            key: 3,
            hint: 'Alexandr Hamilton Main Song',
            image: 'https://media.vanityfair.com/photos/55a6a0fe9e9755183d972088/16:9/w_1280,c_limit/t-culture-list-hamilton.jpg',
            mainText: 'Alexandr Hamilton Main Song',
            title: '',
            linkToMaterial: 'https://music.yandex.ru/album/2972890/track/25250614',
            tasks: [
                {russianWord: 'сирота', correctAnswer: 'orphan', complexity: 60},
                {russianWord: 'убожество ', correctAnswer: 'squalor', complexity: 60},
                {russianWord: 'бедный ', correctAnswer: 'impoverished', complexity: 60},
                {russianWord: 'самоучка', correctAnswer: 'self-starter', complexity: 60},
                {russianWord: 'устав', correctAnswer: 'charter', complexity: 60},
                {russianWord: 'быть настороже', correctAnswer: 'keep his guard up', complexity: 60},
                {russianWord: 'опустошение ', correctAnswer: 'devastation', complexity: 60},
                {russianWord: 'капать', correctAnswer: 'drip', complexity: 60},
                {russianWord: 'канализация', correctAnswer: 'drain', complexity: 60},
                {russianWord: 'припев', correctAnswer: 'refrain', complexity: 60},
                {russianWord: 'завещание', correctAnswer: 'testament', complexity: 60},
                {russianWord: 'погрязший в долгах', correctAnswer: 'debt-ridden', complexity: 60},
                {russianWord: 'прикованный к постели ', correctAnswer: 'bed-ridden', complexity: 60},
                {russianWord: 'запах', correctAnswer: 'scent', complexity: 60},
                {russianWord: 'покончить жизнь самоубийством', correctAnswer: 'commit suicide', complexity: 60},
                {russianWord: 'постоять за себя', correctAnswer: 'fend for yourself', complexity: 60},
                {russianWord: 'научный труд', correctAnswer: 'treatise', complexity: 60},
                {russianWord: 'проницательный', correctAnswer: 'astute', complexity: 60},
                {russianWord: 'обездоленный', correctAnswer: 'destitute', complexity: 60},
                {russianWord: 'сахарный тростник', correctAnswer: 'sugar cane', complexity: 60},
                {russianWord: 'гавань', correctAnswer: 'harbor', complexity: 60},
                {russianWord: 'жесткий', correctAnswer: 'tough', complexity: 60},
                {russianWord: 'возмущение', correctAnswer: 'outrage', complexity: 60},
                {russianWord: 'пропитание', correctAnswer: 'sustenance', complexity: 60},
                {russianWord: 'высокомерный', correctAnswer: 'arrogant', complexity: 60},
                {russianWord: 'царапины', correctAnswer: 'scratching', complexity: 60},
                {russianWord: 'ловкий', correctAnswer: 'slick', complexity: 60},
                {russianWord: 'резюмировать', correctAnswer: 'recap', complexity: 60},
                {russianWord: 'кувырок', correctAnswer: 'flip', complexity: 60},
                {russianWord: 'тезка', correctAnswer: 'namesake', complexity: 60},
                {russianWord: 'игральная кость', correctAnswer: 'dice', complexity: 60},
                {russianWord: 'наркотик', correctAnswer: 'dope', complexity: 60}
            ]
        },
        {
            key: 4,
            hint: 'Godel english lessons',
            image: 'https://cdn.eventfinda.co.nz/uploads/events/transformed/1162486-520708-34.jpg?v=2',
            mainText: 'Godel english lessons',
            title: '',
            linkToMaterial: '',
            tasks: [
                {russianWord: 'selfish behavior', correctAnswer: 'selfish streak', complexity: 60},
                {russianWord: 'bright imagination', correctAnswer: 'vivid imagination', complexity: 60},
                {russianWord: 'smart', correctAnswer: 'razor sharp mind', complexity: 60},
                {russianWord: 'cruelly, strongly', correctAnswer: 'fiercely', complexity: 60},
                {russianWord: 'quick decisions', correctAnswer: 'snap decisions', complexity: 60},
                {russianWord: 'took offense', correctAnswer: 'bear a grudge', complexity: 60},
                {russianWord: 'nature', correctAnswer: 'temper', complexity: 60},
                {russianWord: 'sure', correctAnswer: 'confident', complexity: 60},
                {russianWord: 'keep cool', correctAnswer: 'keep your temper', complexity: 60},
                {russianWord: 'I like', correctAnswer: 'I am fond of', complexity: 60},
                {russianWord: 'exceedingly', correctAnswer: 'supremely', complexity: 60},
                {russianWord: 'hysterical', correctAnswer: 'throw a tantrum', complexity: 60},
                {russianWord: 'abide, keep calm about smth', correctAnswer: 'come to terms with', complexity: 60},
                {russianWord: 'to fraud smb', correctAnswer: 'deceive', complexity: 60},
                {russianWord: 'вариться в собств соку', correctAnswer: 'to stew in one`s own juices', complexity: 60},
                {russianWord: 'быть сдавленным', correctAnswer: 'to be sandwiched', complexity: 60},
                {russianWord: 'подсластить пилюлю', correctAnswer: 'to sugarcoat smth', complexity: 60},
                {russianWord: 'папик', correctAnswer: 'sugar daddy', complexity: 60},
                {russianWord: 'хорошо устроиться', correctAnswer: 'to be on a gravy train', complexity: 60},
                {russianWord: 'лентяй', correctAnswer: 'lazy bone / coach potato', complexity: 60},
                {russianWord: 'расписание', correctAnswer: 'timetable', complexity: 60},
                {russianWord: 'персик', correctAnswer: 'peach', complexity: 60},
                {russianWord: 'малина', correctAnswer: 'raspberries', complexity: 60},
                {russianWord: 'груша', correctAnswer: 'pear', complexity: 60},
                {russianWord: 'свинина', correctAnswer: 'pork', complexity: 60},
                {russianWord: 'баранина', correctAnswer: 'lamb', complexity: 60},
                {russianWord: 'говядина', correctAnswer: 'beef', complexity: 60},
                {russianWord: 'дыня', correctAnswer: 'melon', complexity: 60},
                {russianWord: 'зелёная фасоль', correctAnswer: 'green beans', complexity: 60},
                {russianWord: 'свекла', correctAnswer: 'beetroot', complexity: 60},
                {russianWord: 'лосось', correctAnswer: 'salmon', complexity: 60},
                {russianWord: 'виноград', correctAnswer: 'grape', complexity: 60},
                {russianWord: 'кабачок', correctAnswer: 'courgette', complexity: 60},
                {russianWord: 'мидия', correctAnswer: 'mussel', complexity: 60},
                {russianWord: 'креветка', correctAnswer: 'prawn', complexity: 60},
                {russianWord: 'баклажан', correctAnswer: 'aubergine', complexity: 60},
                {russianWord: 'перец', correctAnswer: 'pepper', complexity: 60},
                {russianWord: 'тунец', correctAnswer: 'tuna', complexity: 60},
                {russianWord: 'варить', correctAnswer: 'boil', complexity: 60},
                {russianWord: 'запеченый', correctAnswer: 'baked', complexity: 60},
                {russianWord: 'жарить', correctAnswer: 'fry', complexity: 60},
                {russianWord: 'Я сойду с ума', correctAnswer: 'I will go bananas', complexity: 60},
                {russianWord: 'все путем', correctAnswer: 'everything is on a track', complexity: 60},
                {russianWord: 'use your brain, dummy', correctAnswer: 'to use your noodles', complexity: 60},
                {russianWord: 'не в моем вкусе', correctAnswer: 'not my cup of tea', complexity: 60},
                {russianWord: 'пустяковое дело', correctAnswer: 'a piece of cake', complexity: 60},
                {russianWord: 'щепотка', correctAnswer: 'pinch', complexity: 60},
                {russianWord: 'воспринимать со скепсисом', correctAnswer: 'to take with a pinch of salt', complexity: 60},
                {russianWord: 'ценное, как ценица ока', correctAnswer: 'the apple of my eye', complexity: 60},
                {russianWord: 'быть невозмутимым', correctAnswer: 'as cool as a cucumber', complexity: 60},
                {russianWord: 'быть оживленным', correctAnswer: 'full of beans', complexity: 60},
                {russianWord: 'умаслить', correctAnswer: 'to butter someone up', complexity: 60},
                {russianWord: 'соус', correctAnswer: 'dressing', complexity: 60},
                {russianWord: 'дикарь', correctAnswer: 'savage', complexity: 60},
                {russianWord: 'время отъедаться', correctAnswer: 'time to pig out', complexity: 60},
                {russianWord: 'проглотить пиццу (быстро)', correctAnswer: 'scarf down pizza', complexity: 60},
                {russianWord: 'отщипнуть/перекус (чипсы и тд)', correctAnswer: 'nibble', complexity: 60},
                {russianWord: 'пастись/перекусывать на ходу', correctAnswer: 'graze', complexity: 60},
                {russianWord: 'покушать средне (гамбургер и тд)', correctAnswer: 'bite', complexity: 60},
                {russianWord: 'собираюсь перекусить чем то средним', correctAnswer: 'Im going to go for a bite', complexity: 60},
                {russianWord: 'причмокивать, чавкать', correctAnswer: 'munch', complexity: 60},
                {russianWord: 'сьесть до крошки (что то дорогое, вкусное)', correctAnswer: 'devour', complexity: 60},
                {russianWord: 'плюнуть', correctAnswer: 'spit', complexity: 60},
                {russianWord: 'кушать мало', correctAnswer: 'eat like a bird', complexity: 60},
                {russianWord: 'беспорядок с едой', correctAnswer: 'looks like a dog breakfast', complexity: 60},
                {russianWord: 'жрать как лошадь (образ жизни)', correctAnswer: 'eat like a horse', complexity: 60},
                {russianWord: 'vulgar', correctAnswer: 'very rude', complexity: 60},
                {russianWord: 'brief', correctAnswer: 'very short', complexity: 60},
                {russianWord: 'dull', correctAnswer: 'very boring/stupid', complexity: 60},
                {russianWord: 'superb', correctAnswer: 'very good', complexity: 60},
                {russianWord: 'scalding', correctAnswer: 'very hot', complexity: 60},
                {russianWord: 'freezing', correctAnswer: 'very cold', complexity: 60},
                {russianWord: 'ravenous', correctAnswer: 'very hungry', complexity: 60},
                {russianWord: 'sluggish', correctAnswer: 'very slow', complexity: 60},
                {russianWord: 'rapid', correctAnswer: 'very fast', complexity: 60},
                {russianWord: 'exhausted', correctAnswer: 'very tired', complexity: 60},
                {russianWord: 'destitute', correctAnswer: 'very poor', complexity: 60},
                {russianWord: 'wealthy', correctAnswer: 'very rich', complexity: 60},
                {russianWord: 'пить жадно, большими глотками', correctAnswer: 'swig', complexity: 60},
                {russianWord: 'отпивать', correctAnswer: 'sip', complexity: 60},
                {russianWord: 'drink/eat greedily', correctAnswer: 'guzzle', complexity: 60},
                {russianWord: 'поперхнуться', correctAnswer: 'choke', complexity: 60},
                {russianWord: 'употреблять кофе', correctAnswer: 'consume coffee', complexity: 60},
                {russianWord: 'Выпить шот крепкого алкоголя', correctAnswer: 'Take shot in a bar', complexity: 60},
                {russianWord: 'выпить залпом, не прерываясь', correctAnswer: 'slug', complexity: 60},
                {russianWord: 'kind of drink (напиток)', correctAnswer: 'kind of beverage', complexity: 60},
                {russianWord: 'вода из под крана', correctAnswer: 'tap water', complexity: 60},
                {russianWord: 'обычная вода, без газа', correctAnswer: 'still water', complexity: 60},
                {russianWord: 'вода с газом', correctAnswer: 'sparkling water', complexity: 60},
                {russianWord: 'cola, sprite etc', correctAnswer: 'soft drinks/pop', complexity: 60},
                {russianWord: 'vodka, scotch etc', correctAnswer: 'hard liquor', complexity: 60},
                {russianWord: 'трезвенник', correctAnswer: 'teetotaler', complexity: 60},
                {russianWord: 'воздержаться от выпивки [в данный момент]', correctAnswer: 'abstain from drinking', complexity: 60},
                {russianWord: 'you do not want to eat', correctAnswer: 'be of your food', complexity: 60},
                {russianWord: 'smth cannot be obtained in sufficient amounts', correctAnswer: 'shortage', complexity: 60},
                {russianWord: 'слюнки потекли', correctAnswer: 'make my mouth water', complexity: 60},
                {russianWord: 'пролить выпивку', correctAnswer: 'spill your drink', complexity: 60},
                {russianWord: 'крепкие напитки', correctAnswer: 'stiff drink', complexity: 60},
                {russianWord: 'how do you do?', correctAnswer: 'how is it rolling?', complexity: 60},
                {russianWord: 'how are you?', correctAnswer: 'how are you holding up?', complexity: 60},
                {russianWord: 'very busy', correctAnswer: 'have a lot on my plate', complexity: 60},
                {russianWord: 'all well', correctAnswer: 'everything is on a track', complexity: 60},
                {russianWord: 'deadlines drive me nut', correctAnswer: 'deadlines make me go bananas', complexity: 60},
                {russianWord: 'what did you do?', correctAnswer: 'what have you been up to?', complexity: 60},
                {russianWord: 'пока все хорошо', correctAnswer: 'So far so good', complexity: 60},
                {russianWord: 'все по-старому, все по-старому', correctAnswer: 'same old, same old', complexity: 60},
                {russianWord: 'перегружены работой и недоплачивают', correctAnswer: 'overworked and underpaid', complexity: 60},
                {russianWord: 'big portion[of food]', correctAnswer: 'substantial', complexity: 60},
                {russianWord: 'food likely to decay or go bad quickly.', correctAnswer: 'perishable', complexity: 60},
                {russianWord: 'decompose', correctAnswer: 'decay', complexity: 60},
                {russianWord: 'good taste/moral integrity[person]', correctAnswer: 'decent', complexity: 60},
                {russianWord: 'a large enjoyable meal/luxurious', correctAnswer: 'slap-up meal', complexity: 60},
                {russianWord: 'гурман', correctAnswer: 'gourmet', complexity: 60},
                {russianWord: 'пощёчина', correctAnswer: 'slap-up', complexity: 60},
                {russianWord: 'я сегодня туплю', correctAnswer: 'I have been a bit of potato today', complexity: 60},
                {russianWord: 'strong alcohol', correctAnswer: 'stiff drink', complexity: 60},
                {russianWord: '', correctAnswer: '', complexity: 60},
                {russianWord: '', correctAnswer: '', complexity: 60},
            ]
        },
        {
            key: 5,
            hint: 'Joe List: I Hate Myself - Full Special',
            image: createYouTubeImageLink('odtAJ2kPdqc'),
            mainText: 'Joe List: I Hate Myself - Full Special',
            title: '',
            linkToMaterial: 'https://www.youtube.com/watch?v=odtAJ2kPdqc&t=134s&ab_channel=ComedyCentralStand-Up',
            tasks: [
                {russianWord: 'шея', correctAnswer: 'neck', complexity: 60},
                {russianWord: 'леденец', correctAnswer: 'lollipop', complexity: 60},
                {russianWord: 'разорванный', correctAnswer: 'torn', complexity: 60},
                {russianWord: 'виновный', correctAnswer: 'guilty', complexity: 60},
                {russianWord: 'зевать', correctAnswer: 'yawn [ён]', complexity: 60},
                {russianWord: 'скончаться', correctAnswer: 'pass away', complexity: 60},
                {russianWord: 'нервирующий', correctAnswer: 'unnerving', complexity: 60},
                {russianWord: 'расслабиться ', correctAnswer: 'ease back', complexity: 60},
                {russianWord: 'одеяло', correctAnswer: 'blanket', complexity: 60},
                {russianWord: 'бесить', correctAnswer: 'piss off', complexity: 60},
                {russianWord: 'похмелье ', correctAnswer: 'hangover', complexity: 60},
                {russianWord: 'связь', correctAnswer: 'bond', complexity: 60},
                {russianWord: 'вопиющий', correctAnswer: 'egregious', complexity: 60},
                {russianWord: 'осмотрительность', correctAnswer: 'discretion', complexity: 60},
                {russianWord: 'выскочить', correctAnswer: 'pop out', complexity: 60},
                {russianWord: 'крендель', correctAnswer: 'pretzel', complexity: 60},
                {russianWord: 'салфетка', correctAnswer: 'napkin', complexity: 60},
                {russianWord: 'приучать', correctAnswer: 'accustom', complexity: 60},
                {russianWord: 'закрасить', correctAnswer: 'paint off', complexity: 60},
                {russianWord: 'глотать', correctAnswer: 'swallow', complexity: 60},
                {russianWord: 'пердеть', correctAnswer: 'fart', complexity: 60},
                {russianWord: 'кишечник', correctAnswer: 'bowel', complexity: 60},
                {russianWord: 'беспокойство', correctAnswer: 'anxiety', complexity: 60},
                {russianWord: 'пшеница', correctAnswer: 'wheat', complexity: 60},
                {russianWord: 'жевать', correctAnswer: 'chew', complexity: 60},
                {russianWord: 'азартная игра', correctAnswer: 'gamble', complexity: 60},
                {russianWord: 'соленые огурцы', correctAnswer: 'pickles', complexity: 60},
                {russianWord: 'гул', correctAnswer: 'buzz', complexity: 60},
                {russianWord: 'ноготь', correctAnswer: 'nail', complexity: 60},
                {russianWord: 'прикус', correctAnswer: 'overbite', complexity: 60},
                {russianWord: 'терроризировать', correctAnswer: 'bully', complexity: 60},
                {russianWord: 'оцепенелый', correctAnswer: 'numb', complexity: 60},
                {russianWord: 'приблизительный', correctAnswer: 'ballpark', complexity: 60},
                {russianWord: 'шишка', correctAnswer: 'nub', complexity: 60},
                {russianWord: 'парик', correctAnswer: 'wig', complexity: 60},
                {russianWord: 'объявиться', correctAnswer: 'show up', complexity: 60},
                {russianWord: 'заряжать', correctAnswer: 'charge up', complexity: 60},
                {russianWord: 'плавать', correctAnswer: 'float', complexity: 60},
                {russianWord: 'телятина', correctAnswer: 'veal', complexity: 60},
                {russianWord: 'метамфетамин', correctAnswer: 'meth', complexity: 60},
                {russianWord: 'солдат', correctAnswer: 'trooper', complexity: 60},
            ]
        },
        {
            key: 6,
            hint: 'Nick Thune: Good Guy - Full Special',
            image: createYouTubeImageLink('HnMSJVRgopc'),
            mainText: 'Nick Thune: Good Guy - Full Special',
            title: '',
            linkToMaterial: 'https://www.youtube.com/watch?v=HnMSJVRgopc',
            tasks: [
                {russianWord: 'установка ', correctAnswer: 'setting up', complexity: 60},
                {russianWord: 'вроде', correctAnswer: 'kinda', complexity: 60},
                {russianWord: 'ключ к разгадке', correctAnswer: 'clue', complexity: 60},
                {russianWord: 'горшок', correctAnswer: 'pot', complexity: 60},
                {russianWord: 'подонок', correctAnswer: 'scumbag', complexity: 60},
                {russianWord: 'выдуманный', correctAnswer: 'coined', complexity: 60},
                {russianWord: 'дверная ручка', correctAnswer: 'doorknob', complexity: 60},
                {russianWord: 'ужалить', correctAnswer: 'sting', complexity: 60},
                {russianWord: 'головорез', correctAnswer: 'cutthroat', complexity: 60},
                {russianWord: 'пирожное', correctAnswer: 'brownie', complexity: 60},
                {russianWord: 'фургон', correctAnswer: 'van', complexity: 60},
                {russianWord: 'проститутка', correctAnswer: 'hooker', complexity: 60},
                {russianWord: 'хвастовство', correctAnswer: 'bragging', complexity: 60},
                {russianWord: 'раковина', correctAnswer: 'sink', complexity: 60},
                {russianWord: 'развод', correctAnswer: 'divorce', complexity: 60},
                {russianWord: 'разрастаться', correctAnswer: 'sprawl out', complexity: 60},
                {russianWord: 'трезвый', correctAnswer: 'sober', complexity: 60},
                {russianWord: 'тонкий', correctAnswer: 'subtle', complexity: 60},
                {russianWord: 'бездельничать', correctAnswer: 'bum out', complexity: 60},
                {russianWord: 'мрачный', correctAnswer: 'somber', complexity: 60},
                {russianWord: 'негодяй', correctAnswer: 'rascal', complexity: 60},
                {russianWord: 'вещи', correctAnswer: 'stuff', complexity: 60},
                {russianWord: 'предвидеть', correctAnswer: 'foresee', complexity: 60},
                {russianWord: 'винт', correctAnswer: 'screw', complexity: 60},
                {russianWord: 'пошел вон', correctAnswer: 'screw you', complexity: 60},
                {russianWord: 'лужайка', correctAnswer: 'lawn', complexity: 60},
                {russianWord: 'размышлять', correctAnswer: 'ponder', complexity: 60},
                {russianWord: 'выпускник ', correctAnswer: 'alumnus [эламнэс]', complexity: 60},
                {russianWord: 'равный', correctAnswer: 'peer', complexity: 60},
                {russianWord: 'сверстники', correctAnswer: 'peers', complexity: 60},
                {russianWord: 'придурок', correctAnswer: 'dork', complexity: 60},
                {russianWord: 'проповедь', correctAnswer: 'sermon', complexity: 60},
                {russianWord: 'лапша', correctAnswer: 'noodles', complexity: 60},
                {russianWord: 'палец на ноге ', correctAnswer: 'toe [тоу]', complexity: 60},
            ]
        },
        {
            key: 7,
            hint: 'Английский по песням',
            image: 'https://avatars.yandex.net/get-music-content/2110367/30528cde.a.9340513-1/m1000x1000',
            mainText: 'Английский по песням',
            title: '',
            linkToMaterial: 'https://music.yandex.by/album/9340513',
            tasks: [
                {russianWord: 'отвечать на телефон', correctAnswer: 'pick up the phone', complexity: 60},
                {russianWord: 'впустить кого то', correctAnswer: 'to let someone in', complexity: 60},
                {russianWord: 'выкинуть кого то', correctAnswer: 'to kick someone out', complexity: 60},
                {russianWord: 'прийти в себя после чего то', correctAnswer: 'to get over something', complexity: 60},
                {russianWord: 'уходи', correctAnswer: 'get gone', complexity: 60},
                {russianWord: 'привычное дело', correctAnswer: 'second nature', complexity: 60},
                {russianWord: 'отшутиться', correctAnswer: 'to laugh something off', complexity: 60},
                {russianWord: 'поддерживать кого то', correctAnswer: 'to get someones back', complexity: 60},
                {russianWord: 'ерунда', correctAnswer: 'no big deal', complexity: 60},
                {russianWord: 'быть в приподнятом настроении', correctAnswer: 'to be up', complexity: 60},
                {russianWord: 'быть в подавленном настроении', correctAnswer: 'to be down', complexity: 60},
                {russianWord: 'терять контроль', correctAnswer: 'to go off the deep end', complexity: 60},
                {russianWord: 'перевернуть ситуацию в свою пользу', correctAnswer: 'to flip the script', complexity: 60},
                {russianWord: 'устроить разборку', correctAnswer: 'to have a bone to pick', complexity: 60},
                {russianWord: 'не повезло [вытянуть короткую спичку]', correctAnswer: 'to get short end of stick', complexity: 60},
                {russianWord: 'поступать подло', correctAnswer: 'to move low', complexity: 60},
                {russianWord: 'детка, малышка', correctAnswer: 'shorty', complexity: 60},
                {russianWord: 'ярый фанат, фанатеть', correctAnswer: 'stan', complexity: 60},
                {russianWord: 'затемнять, омрачать', correctAnswer: 'to cloud', complexity: 60},
                {russianWord: 'оторвать что-нибудь со стены', correctAnswer: 'to rip something off the wall', complexity: 60},
                {russianWord: 'быть польщенным', correctAnswer: 'to be flattered', complexity: 60},
                {russianWord: 'что то закончилось', correctAnswer: 'to be out of something', complexity: 60},
                {russianWord: 'дама в беде', correctAnswer: 'damsel in distress', complexity: 60},
                {russianWord: 'усмирять, приручать', correctAnswer: 'tame', complexity: 60},
                {russianWord: 'неудачник, кто плохо вписывается', correctAnswer: 'misfit', complexity: 60},
                {russianWord: 'запутано, переплетено', correctAnswer: 'twisted', complexity: 60},
                {russianWord: 'сойти с ума', correctAnswer: 'to go out of one\'s mind', complexity: 60},
                {russianWord: 'смотреть пристально', correctAnswer: 'to look  stare', complexity: 60},
                {russianWord: 'елка', correctAnswer: 'spruce', complexity: 60},
                {russianWord: 'омела', correctAnswer: 'mistletoe', complexity: 60},
                {russianWord: 'согласие', correctAnswer: 'consent', complexity: 60},
                {russianWord: 'составлять список', correctAnswer: 'to make a list', complexity: 60},
                {russianWord: 'бодрствовать', correctAnswer: 'to stay awake', complexity: 60},
                {russianWord: 'сани', correctAnswer: 'sleigh [слей]', complexity: 60},
                {russianWord: 'ничего не могу поделать', correctAnswer: 'I cant help it', complexity: 60},
                {russianWord: 'тусовщик', correctAnswer: 'party animal', complexity: 60},
                {russianWord: 'опрокинуть [рюмку]', correctAnswer: 'push it down', complexity: 60},
                {russianWord: 'быть в полном раздрае', correctAnswer: 'to be a mess', complexity: 60},
                {russianWord: 'неподвижный', correctAnswer: 'numb', complexity: 60},
                {russianWord: 'лучшее впереди', correctAnswer: 'the best is yet to come', complexity: 60},
                {russianWord: 'нравится кому то', correctAnswer: 'apeal at someone', complexity: 60},
                {russianWord: 'стоять на месте, бездействовать', correctAnswer: 'stand still', complexity: 60},
                {russianWord: 'очаровательный', correctAnswer: 'adorable', complexity: 60},
            ]
        },
        {
            key: 8,
            hint: 'Mark Normand: Out To Lunch - Full Special',
            image: createYouTubeImageLink('tDolNU89SXI'),
            mainText: 'Mark Normand: Out To Lunch - Full Special',
            title: '',
            linkToMaterial: 'https://www.youtube.com/watch?v=tDolNU89SXI',
            tasks: [
                {russianWord: 'расщепление, декольте', correctAnswer: 'cleavage', complexity: 60},
                {russianWord: 'тучный', correctAnswer: 'obese', complexity: 60},
                {russianWord: 'пойманный', correctAnswer: 'catfished', complexity: 60},
                {russianWord: 'черты', correctAnswer: 'traits', complexity: 60},
                {russianWord: 'подшучивать ', correctAnswer: 'banter', complexity: 60},
                {russianWord: 'облажаться', correctAnswer: 'screw ups', complexity: 60},
                {russianWord: 'выпивка', correctAnswer: 'booze', complexity: 60},
                {russianWord: 'неблагополучная семья', correctAnswer: 'broken home', complexity: 60},
                {russianWord: 'крах', correctAnswer: 'meltdown', complexity: 60},
                {russianWord: 'больной', correctAnswer: 'sore', complexity: 60},
                {russianWord: 'рассеянный', correctAnswer: 'dispelled', complexity: 60},
                {russianWord: 'пятно', correctAnswer: 'stain', complexity: 60},
                {russianWord: 'морщинистый', correctAnswer: 'crinkly', complexity: 60},
                {russianWord: 'ожирение', correctAnswer: 'obesity', complexity: 60},
                {russianWord: 'снисходить', correctAnswer: 'condescend', complexity: 60},
                {russianWord: 'убогий', correctAnswer: 'miserable', complexity: 60},
                {russianWord: 'выявить', correctAnswer: 'elicit', complexity: 60},
                {russianWord: 'намерение', correctAnswer: 'intent', complexity: 60},
                {russianWord: 'наклониться вперед', correctAnswer: 'bend over', complexity: 60},
                {russianWord: 'карлики', correctAnswer: 'midgets', complexity: 60},
                {russianWord: 'потолок', correctAnswer: 'ceiling', complexity: 60},
                {russianWord: 'источает', correctAnswer: 'exudes', complexity: 60},
                {russianWord: 'ряд', correctAnswer: 'aisle [айл]', complexity: 60},
                {russianWord: 'признавать', correctAnswer: 'admit', complexity: 60},
                {russianWord: 'кран', correctAnswer: 'faucet [фосет]', complexity: 60},
                {russianWord: 'жаждущий', correctAnswer: 'thirsty', complexity: 60},
                {russianWord: 'чистить (напр фрукты)', correctAnswer: 'peeling', complexity: 60},
                {russianWord: 'палочка для еды', correctAnswer: 'chopstick', complexity: 60},
                {russianWord: 'головы вниз, оценки вверх', correctAnswer: 'head down grades up', complexity: 60},
                {russianWord: 'прослушка ', correctAnswer: 'bugging', complexity: 60},
                {russianWord: 'булавка', correctAnswer: 'pin', complexity: 60},
                {russianWord: 'меньшинства', correctAnswer: 'minorities', complexity: 60},
                {russianWord: 'дерьмо', correctAnswer: 'crap', complexity: 60},
                {russianWord: 'получить ножевое ранение', correctAnswer: 'get stabbed', complexity: 60},
                {russianWord: 'нетерпимый', correctAnswer: 'bigoted (биготед)', complexity: 60},
                {russianWord: 'подозрительный', correctAnswer: 'sketchy', complexity: 60},
                {russianWord: 'возбужденный ', correctAnswer: 'aroused', complexity: 60},
                {russianWord: 'вытащить это', correctAnswer: 'whip it out', complexity: 60},
                {russianWord: 'смелый', correctAnswer: 'bold', complexity: 60},
                {russianWord: 'призрак', correctAnswer: 'spoke', complexity: 60},
                {russianWord: 'напуганный', correctAnswer: 'spooked', complexity: 60},
                {russianWord: 'разгромить, подавить', correctAnswer: 'crack down', complexity: 60},
                {russianWord: 'попрошайничество', correctAnswer: 'begging', complexity: 60},
                {russianWord: 'ласкать', correctAnswer: 'caress', complexity: 60},
                {russianWord: 'пуповина', correctAnswer: 'umbilical cord', complexity: 60},
                {russianWord: 'шалость', correctAnswer: 'skank', complexity: 60},
                {russianWord: 'извращенец ', correctAnswer: 'kinki', complexity: 60},
                {russianWord: 'мучить', correctAnswer: 'torment', complexity: 60},
                {russianWord: 'устаревший', correctAnswer: 'antiquated', complexity: 60},
                {russianWord: 'резвиться', correctAnswer: 'frolic', complexity: 60},
                {russianWord: 'отвали', correctAnswer: 'back off', complexity: 60},
                {russianWord: 'буквальный ', correctAnswer: 'literal', complexity: 60},
                {russianWord: 'набраться смелости', correctAnswer: 'took guts', complexity: 60},
                {russianWord: 'ворваться', correctAnswer: 'kick in', complexity: 60},
                {russianWord: 'каблуки ', correctAnswer: 'heels', complexity: 60},
                {russianWord: 'шутка ', correctAnswer: 'jiving', complexity: 60},
                {russianWord: 'рекламировать', correctAnswer: 'advertise', complexity: 60},
                {russianWord: 'сексуально возбужденный', correctAnswer: 'horny', complexity: 60},
                {russianWord: 'порог', correctAnswer: 'porch', complexity: 60},
                {russianWord: 'заработная плата', correctAnswer: 'wage', complexity: 60},
                {russianWord: 'эрекция', correctAnswer: 'boner', complexity: 60},
                {russianWord: 'неглубокий', correctAnswer: 'shallow', complexity: 60},
                {russianWord: 'внезапно', correctAnswer: 'sudden', complexity: 60},
                {russianWord: 'молочные продукты', correctAnswer: 'dairy', complexity: 60},
                {russianWord: 'позор', correctAnswer: 'taint', complexity: 60},
                {russianWord: 'смыв', correctAnswer: 'flush', complexity: 60},
                {russianWord: 'мешок', correctAnswer: 'sack', complexity: 60},
                {russianWord: 'внезапно', correctAnswer: 'sudden', complexity: 60},

            ]
        },
        {
            key: 9,
            hint: 'Films, cartoons',
            image: 'https://englishlive.ef.com/blog/wp-content/uploads/sites/2/2015/08/best-british-films-for-learning-english-fast.jpg',
            mainText: 'Films, cartoons',
            title: '',
            linkToMaterial: 'https://www.google.com/search?channel=fs&client=ubuntu&q=Films+in+english',
            tasks: [
                {russianWord: 'священнослужитель', correctAnswer: 'clergyman', complexity: 60},
                {russianWord: 'благоговение', correctAnswer: 'awe', complexity: 60},
                {russianWord: 'конкурс', correctAnswer: 'contest', complexity: 60},
                {russianWord: 'убедить', correctAnswer: 'convince', complexity: 60},
                {russianWord: 'мучения', correctAnswer: 'anguish', complexity: 60},
                {russianWord: 'жуткий', correctAnswer: 'spooky', complexity: 60},
                {russianWord: 'поклонник', correctAnswer: 'worshipper', complexity: 60},
                {russianWord: 'доверие', correctAnswer: 'credibility', complexity: 60},
                {russianWord: 'распятие', correctAnswer: 'crucifix', complexity: 60},
                {russianWord: 'конкурсы', correctAnswer: 'pageantry', complexity: 60},
                {russianWord: 'предположить', correctAnswer: 'presume', complexity: 60},
                {russianWord: 'промежность', correctAnswer: 'crotch', complexity: 60},
                {russianWord: 'преувеличивать', correctAnswer: 'exaggerate', complexity: 60},
                {russianWord: 'божественный', correctAnswer: 'divine', complexity: 60},
                {russianWord: 'лай', correctAnswer: 'bark', complexity: 60},
                {russianWord: 'выполнить', correctAnswer: 'accomplish', complexity: 60},
                {russianWord: 'ставка', correctAnswer: 'stake', complexity: 60},
                {russianWord: 'судорога', correctAnswer: 'cramp', complexity: 60},
                {russianWord: 'преподобный', correctAnswer: 'reverend', complexity: 60},
                {russianWord: 'поступление', correctAnswer: 'admission', complexity: 60},
                {russianWord: 'уничтожить', correctAnswer: 'wipe out', complexity: 60},
                {russianWord: 'бред', correctAnswer: 'delusion', complexity: 60},
                {russianWord: 'расплывчатый', correctAnswer: 'vague', complexity: 60},
                {russianWord: 'ругаться, присягать', correctAnswer: 'swear', complexity: 60},
                {russianWord: 'предписания', correctAnswer: 'stipulations', complexity: 60},
                {russianWord: 'вылететь из головы', correctAnswer: 'slip his mind', complexity: 60},
                {russianWord: 'скука', correctAnswer: 'boredom', complexity: 60},
                {russianWord: 'заповедь', correctAnswer: 'commandment', complexity: 60},
                {russianWord: 'преднамеренно', correctAnswer: 'deliberately', complexity: 60},
                {russianWord: 'верность', correctAnswer: 'fidelity', complexity: 60},
                {russianWord: 'жаждать', correctAnswer: 'covet', complexity: 60},
                {russianWord: 'плод', correctAnswer: 'fetus', complexity: 60},
                {russianWord: 'набожный', correctAnswer: 'devout', complexity: 60},
                {russianWord: 'restricted time on street', correctAnswer: 'curfew', complexity: 60},
                {russianWord: 'материальный', correctAnswer: 'tangible', complexity: 60},
                {russianWord: 'мученик', correctAnswer: 'martyr', complexity: 60},
                {russianWord: 'действующий', correctAnswer: 'incumbent', complexity: 60},
                {russianWord: 'fragile', correctAnswer: 'brittle', complexity: 60},
                {russianWord: 'overestimation', correctAnswer: 'exaggeration', complexity: 60},
                {russianWord: 'запечатанный', correctAnswer: 'sealed', complexity: 60},
                {russianWord: 'трус', correctAnswer: 'coward', complexity: 60},
                {russianWord: 'обида', correctAnswer: 'resentment', complexity: 60},
                {russianWord: 'клетка для домашней птицы', correctAnswer: 'coop', complexity: 60},
                {russianWord: 'голубь', correctAnswer: 'dove', complexity: 60},
                {russianWord: 'приставучий', correctAnswer: 'clingy', complexity: 60},
                {russianWord: 'осанка', correctAnswer: 'posture', complexity: 60},
                {russianWord: 'нечетный, странный', correctAnswer: 'odd', complexity: 60},
                {russianWord: 'to stop', correctAnswer: 'ceases', complexity: 60},
                {russianWord: 'textile', correctAnswer: 'tissue', complexity: 60},
                {russianWord: 'sleeping dream', correctAnswer: 'nap', complexity: 60},
                {russianWord: 'ковер', correctAnswer: 'carpet', complexity: 60},
                {russianWord: 'полый', correctAnswer: 'hollow', complexity: 60},
                {russianWord: 'безмятежность', correctAnswer: 'serenity', complexity: 60},
                {russianWord: 'to fix smth', correctAnswer: 'mend', complexity: 60},
                {russianWord: 'нахмуриться', correctAnswer: 'frown', complexity: 60},
                {russianWord: 'похоронить', correctAnswer: 'bury', complexity: 60},
                {russianWord: 'евангелие', correctAnswer: 'gospel', complexity: 60},
                {russianWord: 'deep', correctAnswer: 'profound', complexity: 60},
                {russianWord: 'община', correctAnswer: 'congregation', complexity: 60},
                {russianWord: 'жертвы', correctAnswer: 'casualties [кажуалтис]', complexity: 60},
                {russianWord: 'проливать', correctAnswer: 'shed', complexity: 60},
                {russianWord: 'нажать на тормоза', correctAnswer: 'tap the brakes', complexity: 60},
                {russianWord: 'раскаяние', correctAnswer: 'remorse', complexity: 60},
                {russianWord: 'насмешка, имитация', correctAnswer: 'mock', complexity: 60},
                {russianWord: 'тупой', correctAnswer: 'obtuse', complexity: 60},
                {russianWord: 'выплюнул его', correctAnswer: 'spat it out', complexity: 60},
                {russianWord: 'паром', correctAnswer: 'ferry', complexity: 60},
                {russianWord: 'лишать', correctAnswer: 'deprive', complexity: 60},
                {russianWord: 'пастух', correctAnswer: 'shepherd', complexity: 60},
                {russianWord: 'добродетель', correctAnswer: 'virtue', complexity: 60},
                {russianWord: 'кто платит тот и музыку заказывает', correctAnswer: 'He who pays the piper calls the tune', complexity: 60},
                {russianWord: 'указ', correctAnswer: 'decree', complexity: 60},
                {russianWord: 'угнетатель', correctAnswer: 'oppressor', complexity: 60},
                {russianWord: 'danger', correctAnswer: 'hazard', complexity: 60},
                {russianWord: 'растрачивать', correctAnswer: 'squander', complexity: 60},
                {russianWord: 'инсульт', correctAnswer: 'stroke'},
                {russianWord: 'таран', correctAnswer: 'ram'},
                {russianWord: 'greatest', correctAnswer: 'maxie'},
                {russianWord: 'a stupid or worthless person', correctAnswer: 'putz'},
                {russianWord: 'плюхнуться', correctAnswer: 'flop'},
                {russianWord: 'русалка', correctAnswer: 'mermaid'},
                {russianWord: 'принять беспорядок', correctAnswer: 'embrace the mess'},
                {russianWord: 'с нетерпением ждать ', correctAnswer: 'long for'},
                {russianWord: 'обманщик', correctAnswer: 'shifty'},
                {russianWord: '', correctAnswer: ''},
            ]
        },
        {
            key: 10,
            hint: 'Вот это английский! Интервью',
            image: 'https://headlineplanet.com/home/wp-content/uploads/2019/10/Natalie-Portman-Fallon-2-1-e1570065821181-1280x720.jpg',
            mainText: 'Вот это английский! Интервью',
            title: '',
            linkToMaterial: 'https://www.youtube.com/playlist?list=PLOheXwuTHHNQ22sSu3jd8D0Gc55Rt-A_V',
            tasks: [
                {russianWord: 'великолепно, шикарно', correctAnswer: 'gorgeous [горджес]', complexity: 60},
                {russianWord: 'шокирующий, сногсшибательный', correctAnswer: 'stunning', complexity: 60},
                {russianWord: 'это началось давно', correctAnswer: 'it goes back a while', complexity: 60},
                {russianWord: 'впоследствии', correctAnswer: 'afterward[s]', complexity: 60},
                {russianWord: 'хозяин, ведущий', correctAnswer: 'host', complexity: 60},
                {russianWord: 'французский поцелуй', correctAnswer: 'french', complexity: 60},
                {russianWord: 'кто либо из нас', correctAnswer: 'either of us', complexity: 60},
                {russianWord: 'иду по улице', correctAnswer: 'walking down the street', complexity: 60},
                {russianWord: 'хорошо сложен', correctAnswer: 'well put together', complexity: 60},
                {russianWord: 'сдержанный', correctAnswer: 'restrained', complexity: 60},
                {russianWord: 'хорошие манеры', correctAnswer: 'well-mannered', complexity: 60},
                {russianWord: 'признавать', correctAnswer: 'acknowledge', complexity: 60},
                {russianWord: 'скупой', correctAnswer: 'mean', complexity: 60},
                {russianWord: 'привыкнуть', correctAnswer: 'to be used to', complexity: 60},
                {russianWord: 'пресс конференция', correctAnswer: 'press', complexity: 60},
                {russianWord: 'неожиданно, из неоткуда', correctAnswer: 'out of nowhere', complexity: 60},
                {russianWord: 'вызвать у кого то мурашки', correctAnswer: 'to give someone chill', complexity: 60},
                {russianWord: 'раздражающе', correctAnswer: 'irritating', complexity: 60},
                {russianWord: 'сделать что то очень удачное', correctAnswer: 'to hit a home run', complexity: 60},
                {russianWord: 'удовлетворяющее', correctAnswer: 'gratifying', complexity: 60},
                {russianWord: 'предпосылка', correctAnswer: 'premise', complexity: 60},
                {russianWord: 'реклама', correctAnswer: 'advertisement [ad]', complexity: 60},
                {russianWord: 'подбегать', correctAnswer: 'run up', complexity: 60},
                {russianWord: 'бросать косые взгляды', correctAnswer: 'side-eying each other', complexity: 60},
                {russianWord: 'вставать', correctAnswer: 'get up', complexity: 60},
                {russianWord: 'душить', correctAnswer: 'strangle', complexity: 60},
                {russianWord: 'обнять', correctAnswer: 'give a hug', complexity: 60},
                {russianWord: 'намного лучше', correctAnswer: 'way better', complexity: 60},
                {russianWord: 'большой, главный', correctAnswer: 'major', complexity: 60},
                {russianWord: 'сжимать, сдавливать', correctAnswer: 'squeeze', complexity: 60},
                {russianWord: 'признание', correctAnswer: 'confession', complexity: 60},
                {russianWord: 'ерзать', correctAnswer: 'squirm [скворм]', complexity: 60},
                {russianWord: 'без отдыха', correctAnswer: 'restlessly', complexity: 60},
                {russianWord: 'считать, почтение', correctAnswer: 'regard', complexity: 60},
                {russianWord: 'не иметь дурных намерений', correctAnswer: 'mean no harm', complexity: 60},
                {russianWord: 'внезапно', correctAnswer: 'all of a sudden', complexity: 60},
                {russianWord: 'запоминать', correctAnswer: 'memorize', complexity: 60},
                {russianWord: 'предполагается', correctAnswer: 'suppose', complexity: 60},
                {russianWord: 'узнать настроения собеседников', correctAnswer: 'read a room', complexity: 60},
                {russianWord: 'широкий диапазон', correctAnswer: 'broad band', complexity: 60},
                {russianWord: 'вводить в заблуждение', correctAnswer: 'misrepresent', complexity: 60},
                {russianWord: 'искажать', correctAnswer: 'distort', complexity: 60},
                {russianWord: 'я тоже нет', correctAnswer: 'neither do I', complexity: 60},
                {russianWord: 'перевернуться', correctAnswer: 'flip out', complexity: 60},
                {russianWord: 'прошло много времени', correctAnswer: 'it`s been a while', complexity: 60},
                {russianWord: 'младенец', correctAnswer: 'toddler', complexity: 60},
                {russianWord: 'увлекаться чем то', correctAnswer: 'to be into smthg', complexity: 60},
                {russianWord: 'лапа', correctAnswer: 'paw', complexity: 60},
                {russianWord: 'ты пробовал что то?', correctAnswer: 'have you done smthg?', complexity: 60},
                {russianWord: 'притворяться', correctAnswer: 'act out', complexity: 60},
                {russianWord: 'отстой, мусор', correctAnswer: 'rubbish', complexity: 60},
                {russianWord: 'отругать кого то', correctAnswer: 'tell someone off', complexity: 60},
                {russianWord: 'привыкнуть', correctAnswer: 'get used to', complexity: 60},
                {russianWord: 'облом', correctAnswer: 'bummer [баммер]', complexity: 60},
                {russianWord: 'если мы заходим так далеко', correctAnswer: 'if we are going that far', complexity: 60},
                {russianWord: 'постоянно', correctAnswer: 'consistently', complexity: 60},
                {russianWord: 'захват, хват', correctAnswer: 'grip', complexity: 60},
                {russianWord: 'действовать так как будто', correctAnswer: 'act as if', complexity: 60},
                {russianWord: 'мы в ударе', correctAnswer: 'we are killing it', complexity: 60},
                {russianWord: 'собеседование', correctAnswer: 'audition', complexity: 60},
                {russianWord: 'предъявлять права на что то', correctAnswer: 'stake claim on smth', complexity: 60},
                {russianWord: 'предположительно', correctAnswer: 'supposedly', complexity: 60},
                {russianWord: 'правдоподобный', correctAnswer: 'plausible', complexity: 60},
                {russianWord: 'ты к чему?', correctAnswer: 'where are you going with this?', complexity: 60},
                {russianWord: 'родственники, народ', correctAnswer: 'folks', complexity: 60},
                {russianWord: 'быть зависимым', correctAnswer: 'be addicted', complexity: 60},
                {russianWord: 'снимать фильм', correctAnswer: 'to shoot a film', complexity: 60},
                {russianWord: 'смягчать, добираться до работы', correctAnswer: 'commute', complexity: 60},
                {russianWord: 'man that make drinks in a bar', correctAnswer: 'bartender', complexity: 60},
                {russianWord: 'my friends', correctAnswer: 'couple friends of mine', complexity: 60},
                {russianWord: 'seemed to be true, is likely', correctAnswer: 'apparently', complexity: 60},
                {russianWord: 'threat', correctAnswer: 'menace', complexity: 60},
                {russianWord: 'average, disgusting', correctAnswer: 'mean', complexity: 60},
                {russianWord: 'remove problem', correctAnswer: 'so relieved', complexity: 60},
                {russianWord: 'students, followers', correctAnswer: 'disciples', complexity: 60},
                {russianWord: 'сериал', correctAnswer: 'series', complexity: 60},
                {russianWord: 'укрыться', correctAnswer: 'hunker down', complexity: 60},
                {russianWord: 'ракета', correctAnswer: 'missile', complexity: 60},
                {russianWord: 'сдерживание', correctAnswer: 'deterrent', complexity: 60},
                {russianWord: 'сарай', correctAnswer: 'barn'},
                {russianWord: 'племянница', correctAnswer: 'niece'},
                {russianWord: 'русло реки', correctAnswer: 'riverbed'},
                {russianWord: 'судебная экспертиза', correctAnswer: 'forensics'},
                {russianWord: 'ремень', correctAnswer: 'strap'},
                {russianWord: 'задворки', correctAnswer: 'boondocks'},
                {russianWord: '', correctAnswer: ''},

            ]
        },
        {
            key: 11,
            hint: 'Вот это английский! Новости',
            image: 'https://i.pinimg.com/originals/12/2d/8d/122d8d2269116d702b730a263b2a4141.jpg',
            mainText: 'Вот это английский! Новости',
            title: '',
            linkToMaterial: 'https://www.youtube.com/watch?v=-FSngDXo6io&list=PLOheXwuTHHNSoe_SAput7WsbnCF-_Z9yb&index=1',
            tasks: [
                {russianWord: 'тревожащие картины', correctAnswer: 'disturbing images', complexity: 60},
                {russianWord: 'солдаты', correctAnswer: 'troops', complexity: 60},
                {russianWord: 'посередине', correctAnswer: 'amid', complexity: 60},
                {russianWord: 'давка толпы', correctAnswer: 'crush [stampedes]', complexity: 60},
                {russianWord: 'десятки тысяч', correctAnswer: 'tens of thousands', complexity: 60},
                {russianWord: 'отчаянный', correctAnswer: 'desperate', complexity: 60},
                {russianWord: 'следовать', correctAnswer: 'ensue', complexity: 60},
                {russianWord: 'последующая', correctAnswer: 'ensuing', complexity: 60},
                {russianWord: 'изъятие, вывод войск', correctAnswer: 'withdrawal', complexity: 60},
                {russianWord: 'руководить', correctAnswer: 'preside over', complexity: 60},
                {russianWord: 'показывать по телевизору', correctAnswer: 'televise', complexity: 60},
                {russianWord: 'обращение', correctAnswer: 'address', complexity: 60},
                {russianWord: 'клятва, пообещать', correctAnswer: 'vow', complexity: 60},
                {russianWord: 'цитата', correctAnswer: 'quote', complexity: 60},
                {russianWord: 'конец цитаты', correctAnswer: 'unquote', complexity: 60},
                {russianWord: 'хребет', correctAnswer: 'backbone', complexity: 60},
                {russianWord: 'осуществить', correctAnswer: 'carry out', complexity: 60},
                {russianWord: 'охотиться', correctAnswer: 'hunt down', complexity: 60},
                {russianWord: 'доказательства', correctAnswer: 'proof', complexity: 60},
                {russianWord: 'идти против чего то', correctAnswer: 'come up against sth', complexity: 60},
                {russianWord: 'сомнения', correctAnswer: 'hesitation', complexity: 60},
                {russianWord: 'преодолеть', correctAnswer: 'overcome', complexity: 60},
                {russianWord: 'подавляющее большинство сомневающихся', correctAnswer: 'vast majority of hesitant', complexity: 60},
                {russianWord: 'быть одержимым кем то', correctAnswer: 'to be obsessed with smone', complexity: 60},
                {russianWord: 'с тех самых пор', correctAnswer: 'ever since', complexity: 60},
                {russianWord: 'управлять мотоциклом', correctAnswer: 'to ride a motorcycle', complexity: 60},
                {russianWord: 'меня спрашивают', correctAnswer: 'I get asked', complexity: 60},
                {russianWord: 'нестись (двигаться очень быстро)', correctAnswer: 'hurtling down [хертлин]', complexity: 60},
                {russianWord: 'шестеренка, передача', correctAnswer: 'gear', complexity: 60},
                {russianWord: 'бурчание', correctAnswer: 'rumbling', complexity: 60},
                {russianWord: 'понятно, очевидно', correctAnswer: 'clearly', complexity: 60},
                {russianWord: 'избирательный участок', correctAnswer: 'polling station', complexity: 60},
                {russianWord: 'передача', correctAnswer: 'transmission', complexity: 60},
                {russianWord: 'биллютень', correctAnswer: 'ballot', complexity: 60},
                {russianWord: 'проголосовать', correctAnswer: 'cast a ballot', complexity: 60},
                {russianWord: 'утверждать', correctAnswer: 'to allege', complexity: 60},
                {russianWord: 'вмешиваться', correctAnswer: 'interfere', complexity: 60},
                {russianWord: 'сомнительный', correctAnswer: 'doubtful', complexity: 60},
                {russianWord: '', correctAnswer: ''},
                {russianWord: '', correctAnswer: ''},
            ]
        },
    ]
}

const INCREMENT_SCORE = "INCREMENT_SCORE"
const RESET_SCORE = "RESET_SCORE"

const INCREASE_COMPLEXITY = "INCREASE_COMPLEXITY"
const DECREASE_COMPLEXITY = "DECREASE_COMPLEXITY"

export const mainPageReducer = (state = initialState, action) => {

    switch (action.type) {

       case INCREASE_COMPLEXITY: {
            const result = cloneDeep(state)
            result.materials.map(material => {
                return material.tasks.map(wordPair => {
                    if (wordPair.russianWord === action.key || wordPair.correctAnswer === action.key) {
                        let actualComplexity = wordPair.complexity >= 100 ? wordPair.complexity : wordPair.complexity + 30
                        wordPair.complexity = actualComplexity
                        return wordPair
                    }
                    return wordPair
                })
            })
            return result;
       }


       case DECREASE_COMPLEXITY: {
            const result = cloneDeep(state)
            result.materials.map(material => {
                return material.tasks.map(wordPair => {
                    if (wordPair.russianWord === action.key || wordPair.correctAnswer === action.key) {
                        wordPair.complexity = wordPair.complexity <= 1 ? 5 : wordPair.complexity - 30
                        return wordPair
                    }
                    return wordPair
                })
            })
            return result;
       }

       case INCREMENT_SCORE: {
            return {...state, score: state.score + 1}
       }

       case RESET_SCORE: {
            return {...state, score: 0}
       }

       default:
            return state;
    }
}

export const increaseComplexityActionCreator = (key) => ({type: INCREASE_COMPLEXITY, key: key})
export const decreaseComplexityActionCreator = (key) => ({type: DECREASE_COMPLEXITY, key: key})

export const incrementScoreActionCreator = () => ({type: INCREMENT_SCORE})
export const resetScoreActionCreator = () => ({type: RESET_SCORE})